# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Compile code
        run: mvn --batch-mode compile
      - name: Run tests
        run: mvn --batch-mode package -Psmoke-test
      - name: Generate Maven test report
        if: failure()
        run: mvn --batch-mode surefire-report:report-only
      - name: Upload test report
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-report
          path: |
            target/surefire-reports
            target/site
